accepted = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Unicode-DFS-2016",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "BSL-1.0",
    "Zlib",
    "OFL-1.1",
    "LicenseRef-UFL-1.0",
    "MIT",
    "ISC",
]
