[package]
name = "warpainter"
version = "0.1.0"
license = "Apache-2.0 WITH LLVM-exception"
edition = "2021"

[profile.release]
debug = true
incremental = true
lto = "off"

[dependencies]
eframe = { version = "0.19.0", default-features = false, features = ["default_fonts", "glow"] }
image = "0.24.3"
rfd = "0.10"
lazy_static = "1.4"
byte-slice-cast = "1.2.1"

[dependencies.uuid]
version = "1.1.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
